name: terraform-plan

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  TF_VERSION: 1.0.2

jobs:
  terrafor-plan:
    runs-on: ubuntu-latest
    name: Create terraform plan

    steps:
      - name: Checkout
        uses: actions/checkout@1.0.0

      - name: Setup AWS credentials
        run: |
          mkdir -p .aws
          echo "[amazeddev]" > .aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> .aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .aws/credentials

      - name: Terraform Init
        uses: sebastianluszczek/lambda_API@dev
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: init
        env:
          AWS_SHARED_CREDENTIALS_FILE: .aws/credentials

      # - name: Terraform Validate
      #   uses: rewindio/terraform-github-actions@master
      #   with:
      #     tf_actions_version: ${{ env.TF_VERSION }}
      #     tf_actions_subcommand: validate
      #   env:
      #     TF_WORKSPACE: ${{ env.WORKSPACE }}
      #     AWS_SHARED_CREDENTIALS_FILE: .aws/credentials
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Plan
        id: terraform-plan
        uses: sebastianluszczek/lambda_API@dev
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: plan
        env:
          AWS_SHARED_CREDENTIALS_FILE: .aws/credentials

      - name: Cleanup AWS Credentials
        run: |
          rm -rf .aws
